---
apiVersion: v1
kind: Pod
metadata:
  name: redis-console
  namespace: _ENVIRONMENT_
spec:
  restartPolicy: Always
  containers:
    - name: redis-console
      image: tarosky/k8s-redis-ha:console-3.0.1
